const cdnUrl = "https://cdn-crownx.winmart.vn/images/chinsu/landingpage/";
const images = {
  homepage: {
    slider_mobile: `${cdnUrl}slider_mobile_new.jpg`,
    slider: `${cdnUrl}slider_1600.jpg`,
    original:`${cdnUrl}original.jpg`,
    pho:`${cdnUrl}pho.jpg`,
    chithien:`${cdnUrl}chi_thien.jpg`,
    truffle:`${cdnUrl}truffle.jpg`,
    original_intro:`${cdnUrl}original_intro.jpg`,
    pho_intro:`${cdnUrl}pho_intro_new.png`,
    chithien_intro:`${cdnUrl}chi_thien_intro_new.png`,
    truffle_intro:`${cdnUrl}truffle_intro_new.png`,
    original_intro_mobile:`${cdnUrl}original_intro_mobile.jpg`,
    pho_intro_mobile:`${cdnUrl}pho_intro_mobile.jpg`,
    chithien_intro_mobile:`${cdnUrl}chi_thien_intro_mobile.jpg`,
    truffle_intro_mobile:`${cdnUrl}truffle_intro_mobile.jpg`,
    video_0:`${cdnUrl}videos/thumb_0.jpg`,
    video_1:`${cdnUrl}videos/thumb_1.jpg`,
    video_2:`${cdnUrl}videos/thumb_2.jpg`,
    video_3:`${cdnUrl}videos/thumb_3_new.jpg`,
    bottom:`${cdnUrl}bottom_594.jpg`,    
  },
  ourStory: {
    banner1:`${cdnUrl}our_story/banner1_1.jpg`,
    banner2:`${cdnUrl}our_story/banner2.jpg`,
    banner3:`${cdnUrl}our_story/banner3.jpg`,
    banner4:`${cdnUrl}our_story/banner4.jpg`,
    original:`${cdnUrl}our_story/original.jpg`,
    pho:`${cdnUrl}our_story/pho.jpg`,
    chi_thien:`${cdnUrl}our_story/chi_thien.jpg`,
    truffle:`${cdnUrl}our_story/truffle.jpg`,
    bottom:`${cdnUrl}our_story/bottom.jpg`,
    banner_mobile1:`${cdnUrl}our_story/banner_mobile1.jpg`,
    banner_mobile2:`${cdnUrl}our_story/banner_mobile2.jpg`,
    banner_mobile3:`${cdnUrl}our_story/banner_mobile3.jpg`,
    banner_mobile4:`${cdnUrl}our_story/banner_mobile4.jpg`,
    banner_mobile5:`${cdnUrl}our_story/banner_mobile5.jpg`,
  },
  products: {
    bottom:`${cdnUrl}bottom_594.jpg`, 
    original_topLeft:`${cdnUrl}detail/original_desc_left1.jpg`,
    original_bottomLeft:`${cdnUrl}detail/original_desc_left2.jpg`,
    original_right:`${cdnUrl}detail/original_desc_right1.jpg`,
    pho_topLeft:`${cdnUrl}detail/pho_desc_left1.jpg`,
    pho_bottomLeft:`${cdnUrl}detail/pho_desc_left2.jpg`,
    pho_right:`${cdnUrl}detail/pho_desc_right1.jpg`,
    chithien_topLeft:`${cdnUrl}detail/chithien_desc_left1.jpg`,
    chithien_bottomLeft:`${cdnUrl}detail/chithien_desc_left2.jpg`,
    chithien_right:`${cdnUrl}detail/chithien_desc_right.jpg`,
    truffle_topLeft:`${cdnUrl}detail/truffle_desc_left1.jpg`,
    truffle_bottomLeft:`${cdnUrl}detail/truffle_desc_left2.jpg`,
    truffle_right:`${cdnUrl}detail/truffle_desc_right.jpg`,
    org_seafood:`${cdnUrl}detail/original_chickend_wing.jpg`,
    org_egg:`${cdnUrl}detail/original_scrambled_egg.jpg`,
    org_cheese:`${cdnUrl}detail/original_cheese.jpg`,
    org_poboys:`${cdnUrl}detail/original_poboys.jpg`,
    org_tacos:`${cdnUrl}detail/original_tacos.jpg`,
    org_sandwich:`${cdnUrl}detail/original_sandwich.jpg`,
    pho_beef1:`${cdnUrl}detail/pho_beef1.jpg`,
    pho_shrimp:`${cdnUrl}detail/pho_shrimp.jpg`,
    pho_mushroom:`${cdnUrl}detail/pho_mushroom.jpg`,
    pho_beef2:`${cdnUrl}detail/pho_beef2.jpg`,
    pho_chicken:`${cdnUrl}detail/pho_chicken.jpg`,
    pho_seafood:`${cdnUrl}detail/pho_seafood.jpg`,
    chithien_burger:`${cdnUrl}detail/chithien_burger.jpg`,
    chithien_burrito:`${cdnUrl}detail/chithien_burrito.jpg`,
    chithien_tacos:`${cdnUrl}detail/chithien_tacos.jpg`,
    chithien_asada:`${cdnUrl}detail/chithien_asada.jpg`,
    chithien_banhmi:`${cdnUrl}detail/chithien_banhmi.jpg`,
    chithien_sandwich:`${cdnUrl}detail/chithien_sandwich.jpg`,
    truffle_french:`${cdnUrl}detail/truffle_french_fries.jpg`,
    truffle_steaks:`${cdnUrl}detail/truffle_steaks.jpg`,
    truffle_pasta:`${cdnUrl}detail/truffle_pasta.jpg`,
    truffle_tomahawk:`${cdnUrl}detail/truffle_tomahawk.jpg`,
    truffle_cheese:`${cdnUrl}detail/truffle_cheese.jpg`,
    truffle_lamb_chops:`${cdnUrl}detail/truffle_lamb_chops.jpg`,
    rel_original:`${cdnUrl}gallery/original.jpg`,
    rel_pho:`${cdnUrl}gallery/pho.jpg`,
    rel_chi_thien:`${cdnUrl}gallery/chi_thien.jpg`,
    rel_truffle:`${cdnUrl}gallery/truffle.jpg`,
    original_detail_1:`${cdnUrl}product_original_1.jpg`,
    original_detail_2:`${cdnUrl}product_original_2.png`,
    original_detail_3:`${cdnUrl}product_original_3.png`,
    original_detail_4:`${cdnUrl}product_original_4.png`,    
    pho_detail_1:`${cdnUrl}product_pho_1_1.png`,
    pho_detail_2:`${cdnUrl}product_pho_2.png`,
    pho_detail_3:`${cdnUrl}product_pho_3.png`,
    pho_detail_4:`${cdnUrl}product_pho_4.png`,
    pho_detail_5:`${cdnUrl}product_pho_5.png`,
    chithien_detail_1:`${cdnUrl}product_chi_thien_1_1.png`,
    chithien_detail_2:`${cdnUrl}product_chi_thien_2.png`,
    chithien_detail_3:`${cdnUrl}product_chi_thien_3.png`,
    chithien_detail_4:`${cdnUrl}product_chi_thien_4.png`,
    chithien_detail_5:`${cdnUrl}product_chi_thien_5.png`,
    truffle_detail_1:`${cdnUrl}product_truffle_1_1.png`,
    truffle_detail_2:`${cdnUrl}product_truffle_2.png`,
    truffle_detail_3:`${cdnUrl}product_truffle_3.png`,
    truffle_detail_4:`${cdnUrl}product_truffle_4.png`,
    truffle_detail_5:`${cdnUrl}product_truffle_5.png`,

    original_intro:`${cdnUrl}original_intro.jpg`,
    pho_intro:`${cdnUrl}pho_intro_new.png`,
    chithien_intro:`${cdnUrl}chi_thien_intro_new.png`,
    truffle_intro:`${cdnUrl}truffle_intro_new.png`,
    original_intro_mobile:`${cdnUrl}/original_intro_mobile.jpg`,
    pho_intro_mobile:`${cdnUrl}pho_intro_mobile.jpg`,
    chithien_intro_mobile:`${cdnUrl}chi_thien_intro_mobile.jpg`,
    truffle_intro_mobile:`${cdnUrl}truffle_intro_mobile.jpg`,
    bottom_original:`${cdnUrl}detail/bottom_original.jpg`,
    bottom_pho:`${cdnUrl}detail/bottom_pho1.jpg`,
    bottom_chi_thien:`${cdnUrl}detail/bottom_chi_thien1.jpg`,
    bottom_truffle:`${cdnUrl}detail/bottom_truffle1.jpg`,
  },
  recipes: {
    banner_top:`${cdnUrl}recipes/banner_top1.jpg`,
    org_seafood:`${cdnUrl}detail/original_chickend_wing.jpg`,
    org_egg:`${cdnUrl}detail/original_scrambled_egg.jpg`,
    org_cheese:`${cdnUrl}detail/original_cheese.jpg`,
    org_poboys:`${cdnUrl}detail/original_poboys.jpg`,
    org_tacos:`${cdnUrl}detail/original_tacos.jpg`,
    org_sandwich:`${cdnUrl}detail/original_sandwich.jpg`,
    pho_beef1:`${cdnUrl}detail/pho_beef1.jpg`,
    pho_shrimp:`${cdnUrl}detail/pho_shrimp.jpg`,
    pho_mushroom:`${cdnUrl}detail/pho_mushroom.jpg`,
    pho_beef2:`${cdnUrl}detail/pho_beef2.jpg`,
    pho_chicken:`${cdnUrl}detail/pho_chicken.jpg`,
    pho_seafood:`${cdnUrl}detail/pho_seafood.jpg`,
    chithien_burger:`${cdnUrl}detail/chithien_burger.jpg`,
    chithien_burrito:`${cdnUrl}detail/chithien_burrito.jpg`,
    chithien_tacos:`${cdnUrl}detail/chithien_tacos.jpg`,
    chithien_asada:`${cdnUrl}detail/chithien_asada.jpg`,
    chithien_banhmi:`${cdnUrl}detail/chithien_banhmi.jpg`,
    chithien_sandwich:`${cdnUrl}detail/chithien_sandwich.jpg`,
    truffle_french:`${cdnUrl}detail/truffle_french_fries.jpg`,
    truffle_steaks:`${cdnUrl}detail/truffle_steaks.jpg`,
    truffle_pasta:`${cdnUrl}detail/truffle_pasta.jpg`,
    truffle_tomahawk:`${cdnUrl}detail/truffle_tomahawk.jpg`,
    truffle_cheese:`${cdnUrl}detail/truffle_cheese.jpg`,
    truffle_lamb_chops:`${cdnUrl}detail/truffle_lamb_chops.jpg`,
    banner_top_mobile:`${cdnUrl}our_story/banner_top_mobile.jpg`,
    banner_detail:`${cdnUrl}recipes/banner_detail.jpg`,
    banner_detail_mobile:`${cdnUrl}recipes/banner_detail_mobile.jpg`,
    banner_detail_tomahawk:`${cdnUrl}recipes/banner_detail_tomalhawk.jpg`,
    banner_detail_tomahawk_mobile:`${cdnUrl}recipes/banner_detail_tomalhawk_mobile.jpg`,
    banner_detail_pho:`${cdnUrl}recipes/banner_detail_pho.jpg`,
    banner_detail_pho_mobile:`${cdnUrl}recipes/banner_detail_pho_mobile.jpg`,
    banner_detail_burger:`${cdnUrl}recipes/banner_detail_burger.jpg`,
    banner_detail_burger_mobile:`${cdnUrl}recipes/banner_detail_burger_mobile.jpg`,
    // banner_detail_pho:`/recipes/banner_detail_pho.jpg`,
    // banner_detail_pho_mobile:`/recipes/banner_detail_pho_mobile.jpg`,
    // banner_detail_burger:`/recipes/banner_detail_burger.jpg`,
    // banner_detail_burger_mobile:`/recipes/banner_detail_burger_mobile.jpg`,

  },
  gallery: {
    original:`${cdnUrl}gallery/original.jpg`,
    pho:`${cdnUrl}gallery/pho.jpg`,
    chi_thien:`${cdnUrl}gallery/chi_thien.jpg`,
    truffle:`${cdnUrl}gallery/truffle.jpg`,
    banner_top:`${cdnUrl}gallery/banner_top1.jpg`,
    gallery1:`${cdnUrl}gallery/gallery1.jpg`,
    gallery2:`${cdnUrl}gallery/gallery2.jpg`,
    gallery3:`${cdnUrl}gallery/gallery3.jpg`,
    gallery4:`${cdnUrl}gallery/gallery4.jpg`,
    gallery5:`${cdnUrl}gallery/gallery5.jpg`,
    mobile1:`${cdnUrl}gallery/mobile1.jpg`,
    mobile2:`${cdnUrl}gallery/mobile2.jpg`,
    mobile3:`${cdnUrl}gallery/mobile3.jpg`,
    mobile4:`${cdnUrl}gallery/mobile4.jpg`,
    mobile5:`${cdnUrl}gallery/mobile5.jpg`,
    mobile6:`${cdnUrl}gallery/mobile6.jpg`,
  },
  news: {
    banner_top: `${cdnUrl}news/banner-top.png`,
    banner_content: `${cdnUrl}news/banner-content.png`,
    banner_top_mobile: `${cdnUrl}news/banner-top-mobile.png`,
    mobile1: `${cdnUrl}news/mobile1.png`,
    mobile2: `${cdnUrl}news/mobile2.png`,
    mobile3: `${cdnUrl}news/mobile3.png`,
    mobile4: `${cdnUrl}news/mobile4.png`,
    // banner_top: '/news/banner-top.png',
    // banner_content: '/news/banner-content.png',
    // banner_top_mobile: `/news/banner-top-mobile.png`,
    // mobile1: `/news/mobile1.png`,
    // mobile2: `/news/mobile2.png`,
    // mobile3: `/news/mobile3.png`,
    // mobile4: `/news/mobile4.png`,
  },
  wtb: {
    jenny_pho: `${cdnUrl}wtb/jenny_pho_crop.jpg`,
    pho_bac: `${cdnUrl}wtb/pho_bac.png`,
    lemongrass: `${cdnUrl}wtb/lemongrass.png`,
    original: `${cdnUrl}wtb/original.png`,
    pho: `${cdnUrl}wtb/pho.png`,
    chi_thien: `${cdnUrl}wtb/chi_thien.png`,
    truffle: `${cdnUrl}wtb/truffle.png`,
    amazon_logo: `${cdnUrl}wtb/amazon-logo.png`,
    // pho_bac: `/wtb/pho_bac.png`,
    // lemongrass: `/wtb/lemongrass.png`,
    // original: `/wtb/original.png`,
    // pho: `/wtb/pho.png`,
    // chi_thien: `/wtb/chi_thien.png`,
    // truffle: `/wtb/truffle.png`,
    // amazon_logo: `/wtb/amazon-logo.png`,
  }
};
export default images;
